# Publishes a draft snapshot, after performing validation to make sure all linux
# packages are stable.
name: Validate and Publish Release

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: "Release id to publish"
        required: true
      package_version:
        description: "Version of the package"
        required: true
      build_run_id:
        description: "Run ID for the build_package.yml workflow that triggered this workflow"
        required: true

jobs:
  publish_release:
    name: "Publish release"
    runs-on: ubuntu-20.04
    steps:
      - name: Publish Release
        id: publish_release
        uses: eregon/publish-release@46913fa2b3f7edc7345ae3c17f6d1b093a54916d # v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
        with:
          release_id: ${{ github.event.inputs.release_id }}

